-------------------------------------------------------------------------------
Test set: online.goudan.test.RedisTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.644 s <<< FAILURE! - in online.goudan.test.RedisTest
test01(online.goudan.test.RedisTest)  Time elapsed: 0.348 s  <<< ERROR!
org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at online.goudan.test.RedisTest.test01(RedisTest.java:29)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to localhost:6379
	at online.goudan.test.RedisTest.test01(RedisTest.java:29)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6379
Caused by: java.net.ConnectException: Connection refused

